### ISSUE TITLE
ar broken with object file names > 16

### ISSUE THREAD

**Issue by sezero** [adtools/amigaos-binutils-2.14#3]
If an object file name is greater than 16 characters  (except for the
nul terminator, e.g. vertexelements.o is bad, vertexelement.o is OK),
then archive manipulation fails with:
```
$ m68k-amigaos-ar x libmgl.a
m68k-amigaos-ar: internal stat error on  RFILENAMES/
```
This issue is not present in 2.9.1 from https://github.com/cahirwpz/amigaos-binutils-2.9.1.git
I don't have an analysis/solution, yet.

**Comment by chenz** [comment]
See also here: https://github.com/adtools/amigaos-binutils-2.14/pull/2

**Comment by sezero** [comment]
Just tried it, yes https://github.com/adtools/amigaos-binutils-2.14/pull/2 seems to fix this issue.

**Comment by jens-maus** [comment]
ok. merge the #2 pull request.
